# action.yml
name: 'Go Semver Release'
description: 'Computes the next, if any, semver for a Git repository and push the semver as Git annotated tag'
inputs:
  repository-url:
    description: 'The Git repository to version'
    required: true
    default: ''
  token:
    description: 'A personnal access token to log in to the Git repository in order to push tags'
    required: true
    default: ''
  tag-prefix:
    description: 'A prefix to append to the semantic version number used to name tag (e.g. "v") and used to match existing tags on remote'
    required: false
    default: ''
  dry-run:
    description: 'Enable dry-run which only computes the next semantic version for a repository, no tags are pushed'
    required: false
    default: "false"
runs:
  using: 'docker'
  image: 'soders/go-semver-release'
  args:
    - --url
    - ${{ inputs.repository-url }}
    - --token
    - ${{ inputs.token }}
    - --tag-prefix
    - ${{ inputs.tag-prefix }}
    - --dry-run
    - ${{ inputs.dry-run }}