name: 'Go Semver Release'
description: 'Computes the next, if any, semver for a Git repository and push it to the repository as a Git annotated tag'
branding:
  icon: 'at-sign'
  color: 'green'
inputs:
  repository-url:
    description: 'The Git repository to version'
    required: true
    default: ''
  token:
    description: 'A personnal access token to log in to the Git repository in order to push tags'
    required: true
    default: ''
  tag-prefix:
    description: 'A prefix to append to the semantic version number used to name tag (e.g. "v") and used to match existing tags on remote'
    required: false
    default: ''
  branch:
    description: 'The branch on which the fetch the commits used to compute the semantic version'
    required: false
    default: ''
  dry-run:
    description: 'Enable dry-run which prevents pushing any tag, only computes the next - if any - semantic version'
    required: false
    default: 'false'
outputs:
  SEMVER:
    description: 'The newly computed version or the current one if no new version were computed'
runs:
  using: 'docker'
  image: 'docker://soders/go-semver-release:latest'
  args:
    - --url
    - ${{ inputs.repository-url }}
    - --token
    - ${{ inputs.token }}
    - --tag-prefix
    - ${{ inputs.tag-prefix }}
    - --branch
    - ${{ inputs.branch }}
    - --dry-run
    - ${{ inputs.dry-run }}