name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Go Build
      run: go build -v ./...

    - name: Go Test
      run: go test -v ./...

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: go-build
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: soders/go-semver-release:latest

  go-semver-release:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
    - uses: actions/checkout@v3

    - name: Hello world action step
      id: hello
      uses: ./
      with:
        repository-url: 'https://github.com/s0ders/go-semver-release.git'
        token: ${{ secrets.GIT_TOKEN }}
