name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  KO_DOCKER_REPO: docker.io/soders
  SEMVER_GIT_REPO_URL: https://github.com/s0ders/go-semver-release.git

jobs:

  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: false

  go-build:
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Go Build
      run: go build -v ./...

    - name: Go Test
      run: go test -v ./...

  ko-build:
    runs-on: ubuntu-latest
    needs: go-build
    outputs:
      release: ${{ steps.gosemver.outputs.NEW_RELEASE }}
      semver: ${{ steps.gosemver.outputs.SEMVER }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Go Semver Release Dryrun
      id: gosemver
      uses: ./
      with:
        repository-url: ${{ env.SEMVER_GIT_REPO_URL }}
        token: ${{ secrets.GIT_TOKEN }}
        tag-prefix: 'v'
        dry-run: 'true'

    - name: output check
      run: echo ${{ steps.gosemver.outputs.NEW_RELEASE }}

    - uses: ko-build/setup-ko@v0.6
      if: ${{ steps.gosemver.outputs.NEW_RELEASE == 'true' }}

    - name: Ko Build Prerelease
      if: ${{ steps.gosemver.outputs.NEW_RELEASE == 'true' }}
      run: cd ./cmd/go-semver-release && ko build -B -t ${{ steps.gosemver.outputs.SEMVER }}-${{ github.sha }}
  
  scan-and-sign:
    runs-on: ubuntu-latest
    needs: ko-build
    if: ${{needs.jobs.ko-build.outputs.release == 'true'}}
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.KO_DOCKER_REPO }}/go-semver-release:${{needs.jobs.ko-build.outputs.semver}}-${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - uses: imjasonh/setup-crane@v0.1
    
    - name: Crane Add Release Tag
      run: |
        crane tag ${{ env.KO_DOCKER_REPO }}/go-semver-release:${{needs.jobs.ko-build.outputs.semver}}-${{ github.sha }} ${{needs.jobs.ko-build.outputs.semver}} && \\ 
        crane tag ${{ env.KO_DOCKER_REPO }}/go-semver-release:${{needs.jobs.ko-build.outputs.semver}}-${{ github.sha }} latest

    - name: Crane Delete Prerelease Tag
      run: crane delete ${{ env.KO_DOCKER_REPO }}/go-semver-release:${{needs.jobs.ko-build.outputs.semver}}-${{ github.sha }}

    - name: Sign Artifacts
      run: |
        cosign sign -a repository=${{ github.repository }} -a commit=${{ github.sha }} -a actor=${{ github.triggering_actor }} \\
        ${{ env.KO_DOCKER_REPO }}/go-semver-release:${{needs.jobs.ko-build.outputs.semver}}
      env:
        COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
        COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}

  go-semver-release:
    runs-on: ubuntu-latest
    needs: scan-and-sign
    if: ${{needs.jobs.ko-build.outputs.release == 'true'}}
    steps:
    - uses: actions/checkout@v3

    - name: Go Semver Release
      uses: ./
      with:
        repository-url: ${{ env.SEMVER_GIT_REPO_URL }}
        token: ${{ secrets.GIT_TOKEN }}
        tag-prefix: 'v'