name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: false

  go-build:
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Go Build
      run: go build -v ./...

    - name: Go Test
      run: go test -v ./...

  ko:
    runs-on: ubuntu-latest
    needs: go-build
    outputs:
      release: ${{ steps.gosemver.outputs.NEW_RELEASE }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Go Semver Release Dryrun
      id: gosemver
      uses: ./
      with:
        repository-url: 'https://github.com/s0ders/go-semver-release.git'
        token: ${{ secrets.GIT_TOKEN }}
        tag-prefix: 'v'
        dry-run: 'true'

    - uses: ko-build/setup-ko@v0.6
      if: ${{ steps.gosemver.outputs.NEW_RELEASE != "false" }}

    - name: ko
      if: ${{ steps.gosemver.outputs.NEW_RELEASE != "false" }}
      run: cd ./cmd/go-semver-release && KO_DOCKER_REPO=${{ secrets.KO_DOCKER_REPO }} ko build -B -t ${{ steps.gosemver.outputs.SEMVER }} -t latest

  go-semver-release:
    runs-on: ubuntu-latest
    needs: ko
    if: ${{needs.ko.outputs.release != "false" }}
    steps:
    - uses: actions/checkout@v3

    - name: Go Semver Release
      uses: ./
      with:
        repository-url: 'https://github.com/s0ders/go-semver-release.git'
        token: ${{ secrets.GIT_TOKEN }}
        tag-prefix: 'v'